name: CI Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Start Xvfb (Virtual Display)
      run: |
        export DISPLAY=:99
        Xvfb :99 -screen 0 1280x720x24 > /dev/null 2>&1 &
        sleep 3

    - name: Run Playwright tests (headfull with virtual display)
      run: npm run test
      env:
        DISPLAY: :99
        CI: true

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: test-results/
        retention-days: 30